- hosts: jenkins
  become: yes
  become_method: sudo
  vars:
    jenkins_docker_image: "billklinefelter/jenkins-qt5"
    jenkins_version: "latest"
    jenkins_config_owner: "jenkins"
    jenkins_config_group: "jenkins"
    jenkins_url: http://127.0.0.1
    jenkins_port: 8080
    jenkins_install_via: "docker"
    jenkins_jobs:
      - "Compile_myBrew"
    jenkins_include_secrets: false
    jenkins_include_custom_files: false
    jenkins_java_opts: "-Djenkins.install.runSetupWizard=false -Dorg.apache.commons.jelly.tags.fmt.timeZone=America/Chicago"

  pre_tasks:
    - name: Installing Docker Python support 
      pip:
        name: docker

    - name: Installing SELinux Python support via yum 
      yum:
        name: python2-libselinux
        state: present
  roles:
    - ansible-jenkins
