```yml
- hosts: jenkins

  vars:
    jenkins_version: "2.190.1"
    jenkins_url: http://jenkins.billklinefelter.com
    jenkins_port: 80
    jenkins_install_via: "docker"
    jenkins_jobs:
        - "Compile"
        - "UnitTest"
        - "SCA"
        - "DeployToArtifactory"
    jenkins_include_secrets: true
    jenkins_include_custom_files: true
    jenkins_custom_files:
    jenkins_custom_plugins:

  roles:
    - emmetog.jenkins
```

